version: "3.8"

services:
  backend:
    build:
      context: blps-online-shop
    container_name: backend-online-shop
    expose:
      - "8080"
    ports:
      - "8080:8080/tcp"
    environment:
      MAIN_PORT: 8080
    networks:
      - onlineshop-network
  cart-consumer-1:
    build:
      context: notification-consumer
    container_name: notification-consumer-1
    expose:
      - "8080"
    ports:
      - "8081:8080/tcp"
    environment:
      CART_PORT: 8080
    networks:
      - onlineshop-network
  cart-consumer-2:
    build:
      context: notification-consumer
    container_name: notification-consumer-2
    expose:
      - "8080"
    ports:
      - "8082:8080/tcp"
    environment:
      CART_PORT: 8080
    networks:
      - onlineshop-network
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-container
    expose:
      - "5672"
      - "15672"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - onlineshop-network
  postgres-shop:
    container_name: postgres-container-online-shop-shop
    image: postgres
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
      - "-c"
      - "max_prepared_transactions=100"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
#    volumes:
#      - db-data2:/data/postgres
    expose:
      - "5432"
    ports:
      - "5557:5432/tcp"
    networks:
      - onlineshop-network
  postgres-um:
    container_name: postgres-container-online-shop-um
    image: postgres
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
      - "-c"
      - "max_prepared_transactions=100"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres

    #    volumes:
    #      - db-data2:/data/postgres
    expose:
      - "5432"
    ports:
      - "5556:5432/tcp"
    networks:
      - onlineshop-network

volumes:
  db-data2:
    driver: local
    name: postgres-pg-data2

networks:
  onlineshop-network:
    driver: bridge